import { NextResponse } from 'next/server';

const CLIENT_ID = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID;
const CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET; // .env.local에 추가 필요
const REFRESH_TOKEN = process.env.SPOTIFY_ADMIN_REFRESH_TOKEN;

// Spotify API 호출 헬퍼
const fetchSpotify = async (url: string, token: string, options: RequestInit = {}) => {
  const res = await fetch(`https://api.spotify.com/v1${url}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
  
  if (!res.ok) {
    const errorBody = await res.text();
    console.error(`Spotify API Error (${url}):`, errorBody);
    throw new Error(`Spotify API Error: ${res.status} ${res.statusText}`);
  }
  return res.json();
};

// 1. 관리자 Access Token 갱신
const getAccessToken = async () => {
  const basic = Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString('base64');
  const response = await fetch('https://accounts.spotify.com/api/token', {
    method: 'POST',
    headers: {
      Authorization: `Basic ${basic}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: REFRESH_TOKEN!,
    }),
  });

  if (!response.ok) {
    throw new Error('Failed to refresh access token');
  }

  const data = await response.json();
  return data.access_token;
};

export async function POST(request: Request) {
  try {
    const { artistNames, festivalName, day } = await request.json();
    
    // ★ 디버깅용 로그: Vercel 로그창에 범인이 누군지 뜹니다.
    console.log("--- [DEBUG] Environment Variables Check ---");
    console.log("1. CLIENT_ID:", CLIENT_ID ? "✅ OK" : "❌ Missing");
    console.log("2. CLIENT_SECRET:", CLIENT_SECRET ? "✅ OK" : "❌ Missing");
    // 보안상 토큰 값 전체를 찍지는 말고 앞 5글자만 찍어서 확인
    console.log("3. REFRESH_TOKEN:", REFRESH_TOKEN ? `✅ OK (${REFRESH_TOKEN.substring(0, 5)}...)` : "❌ Missing");
    console.log("-------------------------------------------");

    if (!REFRESH_TOKEN || !CLIENT_SECRET) {
      // 여기서 멈췄던 겁니다.
      console.error("Critical Error: Missing Environment Variables");
      return NextResponse.json({ error: 'Server misconfiguration: Missing Tokens' }, { status: 500 });
    }

    // 1. 토큰 발급
    const accessToken = await getAccessToken();

    // 2. 아티스트 검색 및 URI 수집 (순서 보장 로직 적용)
    // Promise.all을 사용하여 병렬 처리하되, 결과 배열 순서를 유지
    const searchResults = await Promise.all(
      artistNames.map(async (name: string) => {
        try {
          // 검색
          const searchRes = await fetchSpotify(
            `/search?q=${encodeURIComponent(name)}&type=artist&limit=1`,
            accessToken
          );
          const artist = searchRes.artists?.items[0];
          if (!artist) return [];

          // 인기곡 (한국 시장 기준)
          const topTracksRes = await fetchSpotify(
            `/artists/${artist.id}/top-tracks?market=KR`,
            accessToken
          );
          // 상위 3곡 URI 추출
          return topTracksRes.tracks.slice(0, 3).map((t: any) => t.uri);
        } catch (error) {
          console.error(`Error fetching for ${name}:`, error);
          return [];
        }
      })
    );

    // 2차원 배열 평탄화 (빈 배열 제거 포함)
    const trackUris = searchResults.flat();

    if (trackUris.length === 0) {
      return NextResponse.json({ error: 'No tracks found' }, { status: 404 });
    }

    // 3. 관리자(내) 계정 정보 가져오기
    const me = await fetchSpotify('/me', accessToken);

    // 4. 플레이리스트 생성
    const title = festivalName 
      ? `[${festivalName}] Day ${day} Lineup` 
      : `Wavy Festival Lineup Day ${day}`;
      
    const playlist = await fetchSpotify(`/users/${me.id}/playlists`, accessToken, {
      method: 'POST',
      body: JSON.stringify({
        name: title,
        description: `Generated by Wavy. Lineup for ${festivalName} Day ${day}.`,
        public: false, // 임베드용이므로 false여도 공유 가능 (혹은 true)
      }),
    });

    // 5. 트랙 추가 (한 번에 최대 100곡)
    const chunkSize = 100;
    for (let i = 0; i < trackUris.length; i += chunkSize) {
      const chunk = trackUris.slice(i, i + chunkSize);
      await fetchSpotify(`/playlists/${playlist.id}/tracks`, accessToken, {
        method: 'POST',
        body: JSON.stringify({ uris: chunk }),
      });
    }

    return NextResponse.json({ playlistId: playlist.id });

  } catch (error: any) {
    console.error('Create Playlist Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}